### ISSUE TITLE
POSIX::tmpnam()

### ISSUE THREAD

**Issue by gumiiss** [bkzk/assh#1]
POSIX :: tmpnam () isn't supported in perl version 5.26

Unimplemented: POSIX::tmpnam(): use File::Temp instead at /usr/lib/x86_64-linux-gnu/perl/5.26/POSIX.pm line 185.
Unimplemented: POSIX::tmpnam() at /usr/local/bin/asshpm line 1619.
BEGIN failed--compilation aborted at /usr/local/bin/asshpm line 1619.

**Comment by bkzk** [comment]
Thanks for pointing this out.  POSIX::tmpnam() is is removed totally in Perl 5.26. 
```
perl -MPOSIX -e 'POSIX::tmpnam()'
Unimplemented: POSIX::tmpnam(): use File::Temp instead at -e line 1.
```
I'll try to replace this with File::Temp with next update. But if you will install 'Crypt::OpenPGP' perl module it should solve an issue as the code which trigger this POSIX function is used only when the module is not found on the system.
